[package]
name = "app"
version = "0.1.0"
authors = ["mobile-bungalow <pwmay@ucsc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "*"
dymod = "*"
common = { path = "./common" }
